### ISSUE TITLE
NPE in RsqlJpaConverter.visit

### ISSUE THREAD

**Issue by asual** [perplexhub/rsql-jpa-specification#1]
I just integrated this in a Spring Boot project and it worked just fine for one of the scenarios. Unfortunately I hit an issue in another case where I have a hierarchical parent/child relationship inside an entity class and your logic doesn't set an attribute for properties of associated type inside RsqlJpaSpecification.findPropertyPath.

Thanks for the good work!

**Comment by perplexhub** [comment]
Hi Asual,
Could you share your entity class and the stack trace?
Thank you very much!

**Comment by asual** [comment]
The class in question looks similar to the following:

```
package com.foo;

import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.Data;

@Data
@Entity
@Table(name = "namespaces")
public class Namespace implements Comparable<Namespace> {

    @GeneratedValue
    @Id
    @Column
    private UUID id;

    @Column
    private String name;

    @ManyToOne
    private Namespace parent;

    @Override
    public int compareTo(Namespace namespace) {
        return this.getName().compareTo(namespace.getName());
    }
}
```

The stack trace is empty but the NPE happens at the following line:
https://github.com/perplexhub/rsql-jpa-specification/blob/master/src/main/java/io/github/perplexhub/rsql/jpa/RsqlJpaConverter.java#L62

Executing a `name==value` query works but `parent==value` does not.

**Comment by asual** [comment]
I just tried `parent.id==value` and it got past the problematic line but then hit:

```
java.lang.NoSuchMethodException: java.util.UUID.<init>(java.lang.String)
  at java.lang.Class.getConstructor0(Class.java:3082)
  at java.lang.Class.getConstructor(Class.java:1825)
  at io.github.perplexhub.rsql.jpa.RsqlJpaConverter.castDynamicClass(RsqlJpaConverter.java:163)
  at io.github.perplexhub.rsql.jpa.RsqlJpaConverter.visit(RsqlJpaConverter.java:81)
  at io.github.perplexhub.rsql.jpa.RsqlJpaConverter.visit(RsqlJpaConverter.java:36)
  at cz.jirutka.rsql.parser.ast.ComparisonNode.accept(ComparisonNode.java:70)
```

I suppose that my initial attempt using `parent==value` was incorrect and I kindly ask for the addition of java.lang.UUID type support. You may also consider some simple handling of the NPE just to reduce the confusion.

**Comment by perplexhub** [comment]
I've added the handling of UUID. It should work now. I'll add custom type conversion mapping in the next release. Thanks for your reporting.

```
			else if (dynamicClass.equals(UUID.class)) {
				object = UUID.fromString(value);
			}
```

**Comment by asual** [comment]
Thanks!
