### ISSUE TITLE
divide project in multi modules

### ISSUE THREAD

**Issue by melistik** [perplexhub/rsql-jpa-specification#13]
I would suggest to divide the project in a multi module project in order to use parts also for other implementations. I would like to use your operators + converters as well for an mongo implementation and maybe some other will follow

- rsql-spring (api + helpers without javax.persistence dependency )
  - RSQLComplexConverter.java
  - RSQLOperators.java
  - RSQLSimpleConverter.java
- rsql-jpa-specification
  - RSQLJpaContext.java
  - RSQLVisitorBase.java
  - RSQLJpaPredicateConverter.java
  - RSQLConfig.java (switch logic to auto-configuration)
  - RSQLQueryDslContext.java
  - RSQLQueryDslPredicateConverter.java
  - RSQLSupport.java

What do you think about? I also can help to switch config from @Import(io.github.perplexhub.rsql.RSQLConfig.class) to AutoConfiguration...

I've developed some projects like [commons-auth](https://github.com/rocketbase-io/commons-auth) or  [commons-asset](https://github.com/rocketbase-io/commons-asset) that both have got a jpa + mongo persistence implementation. Would be great to use the same base for both...

**Comment by atkawa7** [comment]
+1

**Comment by perplexhub** [comment]
I've implemented your idea and checked in multi-module branch. Please feel free to comment. Thanks!
https://github.com/perplexhub/rsql-jpa-specification/tree/multi-module

**Comment by atkawa7** [comment]
@perplexhub This is a very good. Just a suggestion. what do think about having the following structure i.e 

```
rsql-spring or rsql-commons(combine spring and common items)
rsql-jpa (jpa without querydsl)
rsql-querydsl(querydsl related files)
rsql-mongo(when mongo comes)
rsql-spring-boot-starter (auto configuration files)
```

**Comment by perplexhub** [comment]
I've rearranged the project structure. What do you think?

- rsql-common - Common stuff
- rsql-jpa - RSQL-JPA support
- rsql-querydsl - RSQL-QueryDSL support
- rsql-support - Backward compatible library
- rsql-jpa-spring-boot-starter - Starter project for RSQL-JPA (auto configuration)
- rsql-querydsl-spring-boot-starter - Starter project for RSQL-QueryDSL (auto configuration)

**Comment by atkawa7** [comment]
@perplexhub the structure looks good to me. Thanks

**Comment by melistik** [comment]
looks great to me as well! thx

**Comment by perplexhub** [comment]
released
