### ISSUE TITLE
escape _

### ISSUE THREAD

**Issue by arvit1** [perplexhub/rsql-jpa-specification#131]
I have description property which contains _ and want to search like this
filter=description=ilike='_' 
this returns all records

I tried even this filter=description=ilike='\_' 
this returns an error
java.lang.IllegalArgumentException: Invalid character found in the request target [/ems/api/events/search?lifecycleId=3&divisionId=2&offset=0&limit=50&table=current&hidden=false&ethidden=false&sort=occuredAt,desc;insertedAt,asc&filter=description=ilike=%22\_%22 ]. The valid characters are defined in RFC 7230 and RFC 3986

is there anyway I can escape _

**Comment by perplexhub** [comment]
Could you try ‘[_]’?

**Comment by arvit1** [comment]
GET http://localhost:8085/ems/api/events/search?lifecycleId=3&divisionId=2&offset=0&limit=50&table=current&hidden=false&ethidden=false&sort=occuredAt,desc;insertedAt,asc&filter=description=ilike='[_]'

gave 400 bad request

I'm using 
implementation group: 'io.github.perplexhub', name: 'rsql-jpa-spring-boot-starter', version: '6.0.4'

**Comment by arvit1** [comment]
Is there a possibility to use the escape character also on other operators for example EQUALS
Thank you for your support

**Comment by ng-galien** [comment]
@arvit1 For sure!
