### ISSUE TITLE
Searching by custom type field doesn't always work

### ISSUE THREAD

**Issue by Ryniu3001** [perplexhub/rsql-jpa-specification#139]
Hi,
we have a problem with searching operation. It doesn't work when we filter by entity field of our custom type. It's work when we are using =ilike= operator, but does not work with =like= operator.

In entity we have our custom type called BIC. To satisfy JPA, we added AttributeConverter 
```
@Converter(autoApply = true)
class BicJpaConverter implements AttributeConverter<BIC, String> {
    @Override
    public String convertToDatabaseColumn(BIC attribute) {
        return attribute.getValue();
    }

    @Override
    public BIC convertToEntityAttribute(String dbData) {
        return BIC.of(dbData);
    }
}
```
Convert method from RSQLVisitorBase class tries to conver query string to BIC class. BIC class have private consructor, so we have added RSQL converter

```
@Configuration
class RsqlConverterConfig {

    @PostConstruct
    void configure() {
        RSQLCommonSupport.addConverter(BIC.class, s -> {
            return BIC.of(s);
        });
    }
}
```

When we call `repository().findAll(RSQLJPASupport.toSpecification(rsqlQuery), pageable)` with query filter `filter=bic=ilike='EBOSPLPW'` it's return success with result.
When we call the same method with query filter `?filter=bic=like='EBOSPLPW'` (like instead of ilike) it throws an exception.

```class java.lang.String cannot be cast to class <my_package>.BIC``` - it tries to call `convertToDatabaseColumn` methos with String parameter - "%EBOSPLPW%".
Somehow, when ilike is used, Hibernate does not use the AttibuteConverter, but it uses it for =like= query.

RSQL library version 6.0.17, Spring Boot version 3.1.5

Someone know how to fix this issue?

**Comment by ng-galien** [comment]
Hi @Ryniu3001 
Is it possible you provide a test case to reproduce the issue? At least

1. The SQL DDL with your target DB
2. The RSQL query

**Comment by Ryniu3001** [comment]
Hi @ng-galien 
I've prepared simple demo repo to reproduce the problem - https://github.com/Ryniu3001/rsql-demo/. Run tests in this project. The "findByBicLike" test fails.

**Comment by ng-galien** [comment]
Hi @Ryniu3001

I submit a PR for your issue, note that you should prefer

```java
RSQLCommonSupport.addEntityAttributeTypeMap(CustomType.class, String.class);
```

If you use `ilike`, `inotlike`or `icase`
