### ISSUE TITLE
No option to specify distinct if using a property map

### ISSUE THREAD

**Issue by basven** [perplexhub/rsql-jpa-specification#14]
Is it possible to add a toSpecification(final String rsqlQuery, final boolean distinct, final Map<String, String>propertyPathMapper) to the RSQLJPASupport class?  Seems to be missing

**Comment by perplexhub** [comment]
Hi @basven, requested methods are added. thanks.

**Comment by basven** [comment]
Great, I'll give it a shot sometime today
