### ISSUE TITLE
Pass a Set<String> of allowed searchable properties

### ISSUE THREAD

**Issue by basven** [perplexhub/rsql-jpa-specification#15]
I would be useful to have the ability to pass in a Set of properties that the query string is allowed to search on.  Throw an exception if the query string contains a property name that is not on the allowed list.

**Comment by perplexhub** [comment]
hi @basven, please check whether these two features (addPropertyWhitelist and addPropertyBlacklist) fit your needs, thanks.

io.github.perplexhub.rsql.RSQLSpecificationSupportTest.testWhitelist()
io.github.perplexhub.rsql.RSQLSpecificationSupportTest.testBlacklist()

**Comment by basven** [comment]
Will play with it today or tomorrow. Thanks for the quick turn-around.
