### ISSUE TITLE
Bug Report: Inconsistent Data Handling with Embedded Entities

### ISSUE THREAD

**Issue by jdmmnn** [perplexhub/rsql-jpa-specification#157]
## Description:
There appears to be an issue with handling embedded entities using RSQL. When querying for embedded entities, the behavior differs depending on whether or not a mapping for an embedded entity is set.

## Steps to Reproduce:
- Clone the repository [rsql-embedded-bug-repository](https://github.com/jdmmnn/rsql-embedded-bug-repository).
- Follow the README instructions to set up and run the project.
- Execute the provided test cases or run the application to reproduce the issue.

## Expected Behavior:
Querying with or without remapping should be possible on embedded entities.

## Actual Behavior:
Querying with mappings on embedded entities leads to an `UnknownPropertyException`.
Without remapping the correct data is returned.

## Additional Information:

- Link to the repository with isolated bug: [rsql-embedded-bug-repository](https://github.com/jdmmnn/rsql-embedded-bug-repository)

## Potential Impact:
This bug impacts any application relying on RSQL queries for embedded entities, particularly when using property mapping functionality, potentially causing data consistency issues and incorrect data retrieval.

**Comment by ng-galien** [comment]
Hi @jdmmnn, thanks for the report, we will try to fix this issue soon.

**Comment by ng-galien** [comment]
@jdmmnn Please have a look on this fix, does it cover your use case?

**Comment by tobjohnbx** [comment]
yes this cover our case, thank you, PR is approved
