### ISSUE TITLE
Support subqueries

### ISSUE THREAD

**Issue by valentinlineiro** [perplexhub/rsql-jpa-specification#16]
Would it be possible to support the additional operators proposed in:

[https://github.com/RutledgePaulV/q-builders](https://github.com/RutledgePaulV/q-builders)

I'm specially interested in the subquery one (=q=). In case it would not be possible, I'd like at least to know how to proceed to extend the current implementation to support it.

**Comment by perplexhub** [comment]
1. "=ex=" The exists clause. It has values of either true or false.
2. "=q=" The subquery clause. It has a string value that itself might be an entire RSQL query.
3. "=re=" A regular expression as a string. The string will be passed as-is to the backend visitor you use, so the regex string must be in the same flavor as the visitor you intend to use (mongo regex vs java regex, etc)

The project you mentioned is database specific features provided by specific library. It's hard to implement those features for a generic library.

In https://github.com/RutledgePaulV/q-builders/blob/develop/src/main/java/com/github/rutledgepaulv/qbuilders/visitors/MongoVisitor.java, which depends on org.springframework.data.mongodb.core.query.Criteria.

In https://github.com/RutledgePaulV/q-builders/blob/develop/src/main/java/com/github/rutledgepaulv/qbuilders/visitors/ElasticsearchVisitor.java which depends on org.elasticsearch.index.query.QueryBuilders.

**Comment by perplexhub** [comment]
All the methods in javax.persistence.criteria.CriteriaBuilder which are returning a Predicate could be supported.
