### ISSUE TITLE
QueryDSL Predicate Like issue

### ISSUE THREAD

**Issue by rzbrth** [perplexhub/rsql-jpa-specification#17]
for filter (**composition=ik= aceclofenac**) QueryDSL Predicate findAll working perfectly fine, 
But when the string value contains space then it is returning null .

eg: (**composition=ik= aceclofenac paracetamol**)
Here space present between **aceclofenac and paracetamol**

**Comment by perplexhub** [comment]
hi, please quote your parameters like composition=ik=' aceclofenac'.

**Comment by alansun2** [comment]
How about If I input  aceclofena'c?

**Comment by perplexhub** [comment]
how about using double quote?

**Comment by alansun2** [comment]
How about If I input aceclo'fena"c? @perplexhub 😄

**Comment by alansun2** [comment]
Thanks @perplexhub
