### ISSUE TITLE
Datetime type like issue

### ISSUE THREAD

**Issue by air10** [perplexhub/rsql-jpa-specification#18]
when I use 1,2,3,  They are only date stirng , work well;
when I use 4,5,6,  They are have time stirng , doesn't work, no return data;

1. createTime=bt=("2020-02-01","2020-02-28")
2. createTime=gt="2020-02-01"
3. createTime=lt="2020-02-01"

4. createTime=bt=("2020-02-01 12:00:00","2020-02-28 12:00:00")
5. createTime=gt="2020-02-01 12:00:00"
6. createTime=lt="2020-02-01 12:00:00"

code:
@CreatedDate
@Temporal(TemporalType.TIMESTAMP)
 private Date createTime;

**Comment by perplexhub** [comment]
Please refer below code snippet for the handling of date/time in the library. It used LocalDate.parse to extract the date value. i.e. the time portion is unable to extract.

`
//io.github.perplexhub.rsql.RSQLVisitorBase.java
if (getValueParserMap().containsKey(dynamicClass)) {
	object = getValueParserMap().get(dynamicClass).apply(value);
} else if (dynamicClass.equals(String.class)) {
	object = value;
} else if (dynamicClass.equals(UUID.class)) {
	object = UUID.fromString(value);
} else if (dynamicClass.equals(Date.class) || dynamicClass.equals(java.sql.Date.class)) {
	object = java.sql.Date.valueOf(LocalDate.parse(value));
} else if (dynamicClass.equals(LocalDate.class)) {
	object = LocalDate.parse(value);
} else if (dynamicClass.equals(LocalDateTime.class)) {
	object = LocalDateTime.parse(value);
} else if (dynamicClass.equals(OffsetDateTime.class)) {
	object = OffsetDateTime.parse(value);
} else if (dynamicClass.equals(ZonedDateTime.class)) {
	object = ZonedDateTime.parse(value);
} else if (dynamicClass.equals(Character.class)) {
	object = (!StringUtils.isEmpty(value) ? value.charAt(0) : null);
} else if (dynamicClass.equals(boolean.class) || dynamicClass.equals(Boolean.class)) {
	object = Boolean.valueOf(value);
} else if (dynamicClass.isEnum()) {
	object = Enum.valueOf(dynamicClass, value);
} else {
	Constructor<?> cons = (Constructor<?>) dynamicClass.getConstructor(new Class<?>[] { String.class });
	object = cons.newInstance(new Object[] { value });
}
`
You could consider to use LocalDateTime, OffsetDateTime or ZonedDateTime for create time field.

**Comment by perplexhub** [comment]
or you can add your own converter by RSQLSupport.addConverter

**Comment by perplexhub** [comment]
Here is a sample

`
	@Test
	public final void testBetweenDateTime() {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
		String rsql = "createDate=bt=('2018-01-01 12:34:56', '2018-12-31 10:34:56')";
		RSQLJPASupport.addConverter(Date.class, s -> {
			try {
				return sdf.parse(s);
			} catch (ParseException e) {
				return null;
			}
		});
		List<User> users = userRepository.findAll(toSpecification(rsql));
		long count = users.size();
		log.info("rsql: {} -> count: {}", rsql, count);
		assertThat(rsql, count, is(11l));
		RSQLJPASupport.removeConverter(Date.class);
	}
`

**Comment by rishi-rana** [comment]
Is this strategy usable if we want to query a jsonb column in postgres?

**Comment by perplexhub** [comment]
I believe if you could query with specification, it should work with some works.
