### ISSUE TITLE
Enum field not handled on dynamicClass

### ISSUE THREAD

**Issue by messaoudi-mounir** [perplexhub/rsql-jpa-specification#2]
Hello,

When an entity contain a Enum field, dynamicClass does'nt handling this type.

Regards,
Mounir

**Comment by einxald** [comment]
You can add value parsers for your custom Classes via `RSQLSupport.addEntityAttributeParser(Type.class, Type::valueOf);`. Then this should work for your Enums as well.

**Comment by messaoudi-mounir** [comment]
Thank you @einxald , i will test it
