### ISSUE TITLE
date =gt= or =lt= not working

### ISSUE THREAD

**Issue by arvit1** [perplexhub/rsql-jpa-specification#20]
hello Perplexhub, 
I have a java.util.Date field which I want to search and when I use ?filter=date=gt=2018-10-20 which I know in db are some above that date I get no results []

thanks 
Arvit

**Comment by perplexhub** [comment]
added a test case which is able to filer out date using =gt=
https://github.com/perplexhub/rsql-jpa-specification/commit/7a040786365c3c3a40bb6678b7c39400e62b0ed7 and ==lt= https://github.com/perplexhub/rsql-jpa-specification/commit/18ce3464c2123f374e27ce82455303a393c55e4b

**Comment by arvit1** [comment]
It worked after adding 	@Temporal(TemporalType.DATE) to the date field in entity
thanks for the support
