### ISSUE TITLE
Add Custom Predicate

### ISSUE THREAD

**Issue by kouzouigh** [perplexhub/rsql-jpa-specification#21]
Hi,
Is there a way to hook a custom predicate, for example when i'm looking for a date i want to use a function predicate instead of the equal predicate defined in the RSQLJPAPredicateConverter.

Example:
Imagine i have a query: date==12/05/2020
And I want to use 
`criteriaBuilder.function(
      "date_trunc", Date.class, criteriaBuilder.literal("day"), context.getPath()
  )`

**Comment by perplexhub** [comment]
Hi @kouzouigh, I've implemented the feature and please check out version 5.0.5-SNAPSHOT and the test case below as a sample.
https://github.com/perplexhub/rsql-jpa-specification/blob/6fbc481735e8ab122f65a28f54f5bf92b51f2548/rsql-jpa/src/test/java/io/github/perplexhub/rsql/RSQLJPASupportTest.java#L49

**Comment by kouzouigh** [comment]
I tested it, it works well, thanks for this feature
