### ISSUE TITLE
MongoDB Querydsl support

### ISSUE THREAD

**Issue by Jamforce** [perplexhub/rsql-jpa-specification#22]
First of all: great work, thank you!
Any plan to add support to MongoDB query via Querydsl?

**Comment by borsch** [comment]
@Jamforce you can use my form of [rsql-mongodb](https://github.com/borsch/rsql-mongodb)

**Comment by mtoobaei** [comment]
> @Jamforce you can use my fork of [rsql-mongodb](https://github.com/borsch/rsql-mongodb)

it does not implement like and ilike operators
