### ISSUE TITLE
Filtering on optional one to one attribute does an inner join

### ISSUE THREAD

**Issue by basven** [perplexhub/rsql-jpa-specification#23]
( I can give more details later if needed ).
I have a Property entity with an optional bi-directional 1 - 1 relation to an address and my filter does something like:
property.address.addressLine1=='street 1', property.somethingelse==<some value>

I would expect to get all properties that have either an address line1 of 'street 1' or where the other property matches some value.  However I only get back properties back that have an address of 'street 1'.
The sql that gets generated is doing an inner join on the address table and I think it is because the following code.

RSQLJPAPredicateConverter around line 53 in the 'if' statement:

`if (isAssociationType(mappedProperty, classMetadata)) {
	Class<?> associationType = findPropertyType(mappedProperty, classMetadata);
	type = associationType;
	String previousClass = classMetadata.getJavaType().getName();
	classMetadata = getManagedType(associationType);

	String keyJoin = root.getJavaType().getSimpleName().concat(".").concat(mappedProperty);
	log.debug("Create a join between [{}] and [{}] using key [{}]", previousClass, classMetadata.getJavaType().getName(), keyJoin);
	root = join(keyJoin, root, mappedProperty);`

The join call defaults to an inner join. I think an extra method is needed to determine if the association is required or not and dependent on that outcome do either an inner or left join. (tried to fix that code formatting issue but apparently github doesn't like quotes or double quotes in code snippets ?)

**Comment by perplexhub** [comment]
Hi @basven, I've created a fix. Could you try version 5.0.5-SNAPSHOT? Please let me know the result, thanks.

**Comment by basven** [comment]
Works great, thanks
