### ISSUE TITLE
Like operation for a LIST type field?

### ISSUE THREAD

**Issue by acyuta1** [perplexhub/rsql-jpa-specification#24]
I have a model entity which has a LIST type field, which stores the value in the form a string (comma separated) in sql. I am trying to implement a custom converter which would return all the samples which has a particular list element.

If the values(of a field) in the DB are 
"A,B,C",
"A",
"B,C",. 
If I provide "A", I want to retrieve both "A,B,C" as well as "A".

This custom converter just returns the sample which has value "A".
```
RSQLJPASupport.addConverter(List.class, s -> {
            try {
                return Arrays.asList(Arrays.asList(s.split(",")));
            }catch (final IllegalArgumentException ex){
                return null;
            }
        });
```

Please help.

**Comment by perplexhub** [comment]
Hi, please refer to https://github.com/perplexhub/rsql-jpa-specification/blob/cc7eec0c2dcdad55fec23727546d9dc0e6aad049/rsql-jpa/src/test/java/io/github/perplexhub/rsql/RSQLJPASupportTest.java#L68

**Comment by perplexhub** [comment]
Hi, you can use =like= operator

**Comment by acyuta1** [comment]
With =like= i get this error: 
"Parameter value [%[A]%] did not match expected type [java.util.List (n/a)]; nested exception is java.lang.IllegalArgumentException: Parameter value [%[modify]%] did not match expected type [java.util.List (n/a)]"

**Comment by perplexhub** [comment]
Assume the name of the field codes, you could use repository.findAll(toSpecification("codes=='A' or codes=='A,' or codes==',A' or codes==',A,'"))

**Comment by perplexhub** [comment]
Can you post your model class and DDL?

**Comment by acyuta1** [comment]
The field is like this:

List<String> listelement;

I tried doing that, but didn't work..
