### ISSUE TITLE
Support for =ilike= for Enums

### ISSUE THREAD

**Issue by SilverSheep** [perplexhub/rsql-jpa-specification#26]
Hello I have an issue as stated in subject:

### prerequisites
**Version** 5.0.5. 

Enum class:
`enum UnitType {
  SIMPLE, COMPLEX, OTHER
}
`

and an entity MyEntity with enum field:
`
private UnitType unitType;
`

### query
?filter=unitType=ilike=MP

### expected result
MyEntity objects with unitType equal to SIMPLE or COMPLEX (for this particular filter)

### actual result
Unfortunately an exception occurs:
org.springframework.dao.InvalidDataAccessApiUsageException: Parameter value [MP] did not match expected type [...UnitType  (n/a)]; 

### summary
Is there any solution to this issue?

Btw. Really nice work with this library Perplexhub :)

**Comment by perplexhub** [comment]
Try adding below in static initialization block
```java
    static {
        RSQLSupport.addEntityAttributeTypeMap(UnitType.class, String.class);
    }
```

**Comment by SilverSheep** [comment]
Already have tried that and I've even tried using RSQLCustomPredicate, but exception is still the same (eventually [%MP%] instead of [MP])

**Comment by SilverSheep** [comment]
@perplexhub Any advice?

**Comment by perplexhub** [comment]
can you post your model and repo class?

**Comment by SilverSheep** [comment]
Repo:
```
@Repository
interface MyEntityRepository extends
        PagingAndSortingRepository<MyEntity, Long>,
        JpaSpecificationExecutor<MyEntity> {
}
```

Model:
```

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

@Entity
@Getter
@Setter
class MyEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Digits(integer = 18, fraction = 0)
    private Long id;

    @NotNull
    private Short year;

    @ManyToOne
    @JoinColumn(name = "unit_id")
    private Unit unit;

    @ManyToOne
    @JoinColumn(name = "process_id")
    private Process process;

    @NotNull
    @Enumerated(EnumType.STRING)
    private Status status = Status.STARTED;

    @Enumerated(EnumType.STRING)
    private UnitType unitType;

    @NotNull
    private String unitName;
}
```

Status entity:
```
enum Status {
    ACTIVE, CANCELLED, FINISHED
}
```

I've changed original names to maintain confidentiality

**Comment by schotten** [comment]
Hello!!! so, i have the same problem i not undertand the resolution (https://github.com/perplexhub/rsql-jpa-specification/issues/26#issuecomment-678368648) in this issue.

I tryed add the RSQLJPASupport.addEntityAttributeTypeMap(MyEnumClass.class, String.class);, but don't know what the QueryDSL

Can you explain more the solution?

My code:
![image](https://user-images.githubusercontent.com/57331623/166970831-401d4c07-aadc-45fa-8a3b-72c0e7449f7f.png)
