### ISSUE TITLE
Null pointer exception when filtering for null on optional ManyToOne relation

### ISSUE THREAD

**Issue by basven** [perplexhub/rsql-jpa-specification#32]
I have a JPA entity that has an optional relationship to itself call 'parent'.
I want to filter and retrieve all entities without a parent using the isnull operator:
filter=parent=isnull=''
This filter however throws a null pointer exception in the RSQLJPAPredicateConverter.findPropertyPath method when it calls         this.accessControl(type, attribute.getName());
because 'attribute' is never set.

I tried working around it by creating a filter where the id is not null but the parent.id is, but that didn't work because the code is doing an inner join:
filter=id=isnotnull='';parent.id=isnull=''
resulted in this sql:
`select ..._ from pi_codes pitype0_ **inner** join pi_codes pitype1_ on pitype0_.parent=pitype1_.id where pitype0_.dtype='pi_type' and (pitype0_.id is not null) and (pitype1_.id is null) `
Since I noticed you have another bug where the code does an inner join instead of a left one and tried using 5.0.6-snapshot but although I don't have an NPE anymore, I do not get any data back either.

**Comment by perplexhub** [comment]
You can create a field which is mapped to the foreign key column, then you can use it for filtering. e.g. parentId=isnull=''
```java
	@Column(name = "parent_id", insertable = false, updatable = false)
	private String parentId;
```
