### ISSUE TITLE
Order By

### ISSUE THREAD

**Issue by arvit1** [perplexhub/rsql-jpa-specification#34]
Hello perplexhub

this is how I use rsql-jpa-specification

    @GetMapping("/suppliers/rsql")
    public DataTablesOutput<SupplierLite> findAllByRsql(@Valid DataTablesInput input, @RequestParam(value = "filter", required = true) String filter) {

        return supplierLiteRepository.findAll(input, RSQLJPASupport.toSpecification(filter));
    }

I want to be able to order by field

thank you for your time
Arvit

**Comment by arvit1** [comment]
I saw the doc and saw this part

Specification<?> specification = RSQLSupport.toSpecification("company.name==name").and(RSQLSupport.toSort("company.name,asc,user.id,desc"));
repository.findAll(specification);

but using the 5.0.7-SNAPSHOT couldn't compile the code ( .and() is missing) 
Thanks again 
Arvit

**Comment by perplexhub** [comment]
You can use org.springframework.data.domain.PageRequest to generate the pageable and use repository.findAll(RSQLSupport.toSpecification(filter), pageable) to generate the results.

```java
	/**
	 * Creates a new {@link PageRequest} with sort parameters applied.
	 *
	 * @param page zero-based page index.
	 * @param size the size of the page to be returned.
	 * @param sort must not be {@literal null}, use {@link Sort#unsorted()} instead.
	 * @since 2.0
	 */
	public static PageRequest of(int page, int size, Sort sort) {
		return new PageRequest(page, size, sort);
	}

	/**
	 * Creates a new {@link PageRequest} with sort direction and properties applied.
	 *
	 * @param page zero-based page index, must not be negative.
	 * @param size the size of the page to be returned, must be greater than 0.
	 * @param direction must not be {@literal null}.
	 * @param properties must not be {@literal null}.
	 * @since 2.0
	 */
	public static PageRequest of(int page, int size, Direction direction, String... properties) {
		return of(page, size, Sort.by(direction, properties));
	}
```
