### ISSUE TITLE
Unkown properties

### ISSUE THREAD

**Issue by jpolitow** [perplexhub/rsql-jpa-specification#35]
Hi, i would like to know how to deal with the properties supplied by frontend app that are not available on filtered entity, currently there is an exception thrown in RSQLJPAPredicateConverter.java:56

> if (!hasPropertyName(mappedProperty, classMetadata)) {
>throw new IllegalArgumentException("Unknown property: " + mappedProperty + " from entity " + classMetadata.getJavaType().getName());
>}

Therefore query is aborted and http error 500 returned.
It would be nice to have a configuration flag that would allow to ignore unknown properties
or some check method that would allow me to return Http code 400 with message which field name is invalid.

**Comment by perplexhub** [comment]
It is not a good idea to suppress the checking, otherwise, someone can manipulate your endpoint with different parameters. You can simply catch the exception and display a proper error message or fallback to a default result.

```java
	@Test(expected = DataAccessException.class)
	public final void testUnknownPropertyCauseException() {
		String rsql = "i==2";
		try {
			userRepository.findAll(toSpecification(rsql));
		} catch (DataAccessException e) {
			log.info("Expected exception", e);
			throw e;
		}
	}
```

**Comment by jpolitow** [comment]
Yes, good point
I was just looking a way to return an error to user that query was invalid because it contains invalid field name(s)
DataAccessException  is so general i cannot distinguish easy way if origin of error is user query or some other source 

But I will look into that, thx for help :)
