### ISSUE TITLE
RSQLJPASupport not working with @DataJpaTest

### ISSUE THREAD

**Issue by gpr-indevelopment** [perplexhub/rsql-jpa-specification#37]
I have been trying to run an integrated test with H2, persisting some data to the database and trying to retrieve it with RSQL and RSQLJPASupport specifications. It works well when the query is empty, but breaks as soon as fill the string with some RSQL syntax.

### Working scenario
```java
@RunWith(SpringRunner.class)
@ActiveProfiles("dev")
@DataJpaTest
public class RSQLFilterIntegratedTest {

    @Autowired
    private ModelDAO modelDAO;

    @Test
    public void works() {
        Model model = saveNewModel();
        String query = ""; // Query is empty...
        Specification<Model> specification = RSQLJPASupport.toSpecification(query);
        List<Model> models = modelDAO.findAll(specification);
    }
}
```

### Broken scenario
```java
@RunWith(SpringRunner.class)
@ActiveProfiles("dev")
@DataJpaTest
public class RSQLFilterIntegratedTest {

    @Autowired
    private ModelDAO modelDAO;

    @Test
    public void works() {
        Model model = saveNewModel();
        String query = "name==some_name";
        Specification<Model> specification = RSQLJPASupport.toSpecification(query);
        List<Model> models = modelDAO.findAll(specification);
    }
}
```
It throws the following exception:
```
org.springframework.dao.InvalidDataAccessApiUsageException: No entity manager bean found in application context; nested exception is java.lang.IllegalStateException: No entity manager bean found in application context
```

Usually `@DataJpaTest` injects a `TestEntityManager` to the application context, so there should be one available for the query. Is it a bug or am I missing something?

**Comment by perplexhub** [comment]
https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/autoconfigure/orm/jpa/TestEntityManager.html

TestEntityManager is not extending javax.persistence.EntityManager.

**Comment by gpr-indevelopment** [comment]
If you take the broken scenario and add a `@AutoConfigureTestEntityManager`, you will see Spring injects an `EntityManager`. Still, the query does not work.

```java
@DataJpaTest
@AutoConfigureTestEntityManager
public class RSQLFilterIntegratedTest {

    @Autowired
    private ModelDAO modelDAO;

    @Autowired
    private EntityManager entityManager; // This is not null. Spring can actually inject it.

    @Test
    public void works() {
        Model model = saveNewModel();
        String query = "name==some_name";
        Specification<Model> specification = RSQLJPASupport.toSpecification(query);
        List<Model> models = modelDAO.findAll(specification);
    }
}
```

**Comment by perplexhub** [comment]
Did you initialize RSQLJPASupport via spring boot starter or initialize manually?

**Comment by gpr-indevelopment** [comment]
I have used its static method only, just like the scenario I gave you. I havent initialized or created an instance of it.

**Comment by perplexhub** [comment]
The starter helps to inject the em to the library.

**Comment by perplexhub** [comment]
io.github.perplexhub.rsql.RSQLCommonSupport.RSQLCommonSupport(Map<String, EntityManager>)

**Comment by perplexhub** [comment]
call new RSQLCommonSupport(Map<String, EntityManager>) to initialize manually

**Comment by gpr-indevelopment** [comment]
It worked! Thank you.
