### ISSUE TITLE
The method addConverter is undefined for the type RSQLJPASupport

### ISSUE THREAD

**Issue by razibrath** [perplexhub/rsql-jpa-specification#38]

**Comment by razibrath** [comment]
The method addConverter(Class<Date>, (<no type> s) -> {}) is undefined for the type RSQLJPASupport while using it for Custom date converter

**Comment by perplexhub** [comment]
Hi razibrath, can you post your code for trouble shooting?

**Comment by razibrath** [comment]
import static io.github.perplexhub.rsql.RSQLJPASupport.*;
// Custom date converter
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
addConverter(Date.class, s -> {
try {
return sdf.parse(s);
} catch (ParseException e) {
return null;
}
});

**Comment by perplexhub** [comment]
I tested io.github.perplexhub.rsql.RSQLJPASupportTest by commenting out 3rd line and remove "RSQLJPASupport." at line 567 and the test case still run positively.

**Comment by razibrath** [comment]
In .class file i can see addConverter method neither present in RSQLJPASupport nor in RSQLCommonSupport.

**Comment by razibrath** [comment]
This issue is solved with  io.github.perplexhub:rsql-jpa-spring-boot-starter:5.0.6  jar
Thanks
