### ISSUE TITLE
How to specify the attributes/columns to retrieve

### ISSUE THREAD

**Issue by kdhrubo** [perplexhub/rsql-jpa-specification#41]
Thanks for the fantastic library.
I played with it and see we can apply various filtering on data including extension via custom filters.
I am thinking is there a possibility also to specify the fields/columns I want to retrieve from database.
Is that feature available? Possible to add if not available.
That's gonna make this api even more compelling.

**Comment by perplexhub** [comment]
Hi, you can use it to generate the queryDSL predicate then you can use
queryDSL to select specific column.

**Comment by kdhrubo** [comment]
I am not able to use querydsl. Straight spring data jpa only.

**Comment by perplexhub** [comment]
Can you create a new model with the columns you want?

**Comment by nickcaballero** [comment]
You can use the criteria query API to do this, using the predicate produced from the RSQLJPAPredicateConverter. You would need to use the CriteriaBuilder to select for a custom constructor.

**Comment by kdhrubo** [comment]
Thanks @nickcaballero @perplexhub 
I get the predictate String and then use 

```
repository.findAll(RSQLSupport.toSpecification(filter));
repository.findAll(RSQLSupport.toSpecification(filter), pageable);
```

Is there a dynamic projection that can be used? Please share your thoughts. 
So besides the filters I would also like to get the columns from my client. 

@nickcaballero I will try your solution if I can do that in the Repository interface method. I do not want to clutter the service code with it. 
 If there is any example will be keen to check it.
