### ISSUE TITLE
Unable to query for keys of an associated HashMap of abstract class

### ISSUE THREAD

**Issue by gpr-indevelopment** [perplexhub/rsql-jpa-specification#43]
Suppose we have an entity that has a `@OneToMany` association with a `HashMap` by using `@MapKey`:

```java
@Entity
@Getter
@Setter
public class ModelA {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @JoinColumn(name = "MODEL_A_ID")
    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, orphanRemoval = true)
    @MapKey(name = "id")
    Map<String, ModelD> keyToModelD = new HashMap<>();

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "MODEL_B_ID", referencedColumnName = "id")
    private final ModelB modelB = new ModelB();
}

@Entity
@Getter
@Setter
public class ModelD {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
}
```

I have tried writing a rsql query in two ways... None of these worked.
1. "keyToModelD==SOME_KEY" - "Unknown property: key from entity" exception.
2. "keyToModelD.key==SOME_KEY" - NullPointerException on RSQLJPAPredicateConverter.java:92

How can we achieve such a query?

**Comment by nickcaballero** [comment]
Well here's the relevant JPQL that might be used to achieve the query - https://www.logicbig.com/tutorials/java-ee-tutorial/jpa/jpql-map-key-value-entry.html.

Are you trying to match the `ModelA` instances that have a `ModelD` with a specific ID?

**Comment by gpr-indevelopment** [comment]
@nickcaballero actually, querying with "keyToModelID.id==1" actually finds it.
After some testing, I realized that we can query by the map's key if ModelD also had a "key" attribute, with the same value.

**Comment by gpr-indevelopment** [comment]
My problem is a little bit more complicated tho...
```java
@Entity
public class ModelA {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @JoinColumn(name = "MODEL_A_ID")
    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, orphanRemoval = true)
    @MapKey(name = "key")
    Map<String, Abstract> keyToAbstract = new HashMap<>();
}

@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "ImplType")
public abstract class Abstract {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String key;
}

@Entity
@DiscriminatorValue("ImplA")
public class ImplA extends Abstract{

    private boolean isAlive;

    private String path;
}

@Entity
@DiscriminatorValue("ImplB")
public class ImplB extends Abstract{

    private String path;

    private Integer quantity;
}
```

I can query for attributes on the `Abstract` class no problem. **But, I cant seem to query for attributes on the `Impl` classes, even though they use the single table strategy.** I have tried things like:

"keyToAbstract.isAlive==true"
"keyToAbstract.path==SOME_PATH"

A similar situation was reported by this [SO question](https://stackoverflow.com/questions/25624768/jpa-criteria-query-over-an-entity-hierarchy-using-single-table-inheritance).

You can find a running scenario of this problem [here](https://github.com/gpr-indevelopment/rsql-attr-converter-scenario).

**Comment by perplexhub** [comment]
Did you try this `Map<String, ImplA> keyToAbstract = new HashMap<>();` ?

**Comment by gpr-indevelopment** [comment]
I could, but then I would lose the abstraction...
I have `ImplA` and `ImplB` that extend `Abstraction`, and I dont want to have a hashmap for each one of them in `ModelA`. I want to be able to persist any data of the implementation classes in the same table (Abstract table) just like the `@Inheritance` strategy do.

**Comment by perplexhub** [comment]
Is it possible to use abstract model for persistence and concrete model for
query?

Gabriel Robaina <notifications@github.com> 於 2020年12月17日週四 下午11:07寫道：

**Comment by gpr-indevelopment** [comment]
Yes. Thats similar to what I intend on doing. I am trying to query the database for ModelA entites that are associated to a certain attribute's value of an `Abstract` **implementation**. The problem occurs when that attribute exists on the implementation, but not on the superclass.

@perplexhub do you have any suggestions? Can you give us an example of that using rsql?

**Comment by perplexhub** [comment]
I believe you will have more flexibility if you use the QueryDSL one.

**Comment by gpr-indevelopment** [comment]
Maybe. But looking at this [SO answer](https://stackoverflow.com/questions/25624768/jpa-criteria-query-over-an-entity-hierarchy-using-single-table-inheritance) it seems achieveable with this lib. What do you think?

I prefer using rsql and this lib due to the ease of implementation.

**Comment by perplexhub** [comment]
I mean you can use [rsql-querydsl-spring-boot-starter] RSQLSupport.toPredicate to generate BooleanExpression, then you can apply some technique like [SO](https://stackoverflow.com/questions/57724240/querydsl-how-to-downcast-a-join-entity)

**Comment by gpr-indevelopment** [comment]
But why isnt that achieveable with something like "keyToAbstract.path==SOME_PATH" or "keyToAbstract.quantity==2"? Maybe `RSQLJPASupport` doesnt support it now, but it could be an improvement to be made.

**Comment by gpr-indevelopment** [comment]
Is this what you meant?
The following test fails because `ImplA` does not have a `keyToAbstract` field. A similar test substituting `QImlA` for `QModelA` throws an error because there is no `path` property for the `Abstract` class.
```java
@Test
public void queryDslAndRsql_findByImplAPathOnQImplA_finds() {
    // given
    ModelA modelA = new ModelA();
    modelA.getKeyToAbstract().put("SOME_KEY", new ImplA(true, "SOME_PATH"));
    ModelA savedModel = modelRepository.save(modelA);
    // then
    Map<String, EntityManager> stringToEm = new HashMap<>();
    stringToEm.put("em", testEntityManager.getEntityManager());
    RSQLQueryDslSupport rsqlQueryDslSupport = new RSQLQueryDslSupport(stringToEm);
    BooleanExpression booleanExpression = rsqlQueryDslSupport.toPredicate("keyToAbstract.path==SOME_PATH", QImplA.implA);
    modelRepository.findAll(booleanExpression).forEach(model -> assertThat(model.getId()).isEqualTo(savedModel.getKeyToAbstract().get("SOME_KEY").getId()));
}
```
This does not really fit my needs since I need to change the rsql string to ommit `keyToAbstract` in order for it to work. That is some filter logic just to fulfill a limitation of the filter API that I would rather not do. The main advantage of rsql combined with this lib is the ability of not having to parse a string, nor do any other filter logic on top of the `Predicate` or `Specification`.

**Comment by gpr-indevelopment** [comment]
PR opened for this functionality [here](https://github.com/perplexhub/rsql-jpa-specification/pull/44)
