### ISSUE TITLE
Fix split packages problem

### ISSUE THREAD

**Issue by kh0ma** [perplexhub/rsql-jpa-specification#45]
When using rsql-jpa-specification in Java 9 application and higher there is a possibility to configure java modularity. For security reasons starting from Java 9 they disallow split packages. Due to this fact, there is no possibility to gracefully declare rsql-jpa-specification as a module since we cannot require two modules that declare the same package:
` module xxx reads package io.github.perplexhub.rsql from both rsql.jpa and rsql.common`

I think it is a good idea to get rid of split packages and name them properly.

More info about a similar problem https://stackoverflow.com/a/42358212

**Comment by kh0ma** [comment]
More info https://www.logicbig.com/tutorials/core-java-tutorial/modules/split-packages.html

**Comment by perplexhub** [comment]
It seems we need to merge rsql-common, rsql-jpa and rsql-querydsl into one module and rename the package in those starter modules.

**Comment by kh0ma** [comment]
As a second option, you may also consider propagating module name to the package so:

- maven module rsql-jpa will have package `package io.github.perplexhub.rsql.jpa;`
- maven module rsql-common will have package `package io.github.perplexhub.rsql.common;`
- etcetera...

**Comment by perplexhub** [comment]
Changing the package name will cause compatibility issue.
