### ISSUE TITLE
Verbose logging

### ISSUE THREAD

**Issue by alievrenkut** [perplexhub/rsql-jpa-specification#47]
First thank you for this awesome library. I am using it and love it.

I have a simple issue at line:
https://github.com/perplexhub/rsql-jpa-specification/blob/44edc2960690df5a6883d1621cbeeb7511bab77d/rsql-common/src/main/java/io/github/perplexhub/rsql/RSQLVisitorBase.java#L94

Log level here is info which clutters my console can you change it debug or any other level?

**Comment by nickcaballero** [comment]
+1 Had been meaning to create an issue for this. In the meantime, we have been suppressing the messages by setting the log level to warn.

**Comment by perplexhub** [comment]
Changed to debug level and included to 5.0.9. Thanks.
