### ISSUE TITLE
Custom Predicate With 2 Arguments

### ISSUE THREAD

**Issue by DiogoSouza123** [perplexhub/rsql-jpa-specification#49]
Hi,
Is there any way to create a custom predicate with two arguments?
I need to recreate de operator between, for use into dates because my database uses datetime type and I need to truncate the hour to work as expected.

    public static RSQLCustomPredicate<Date> customPredicateBetweenDate() {
        String nameFunctionDatabase = "BETWEEN";

        String nameQueryUrl = "=dbt=";

        return new RSQLCustomPredicate<>(new ComparisonOperator( nameQueryUrl ), Date.class, input -> {
            Expression<Date> function = input.getCriteriaBuilder().function(nameFunctionDatabase , Date.class, input.getPath());
            return input.getCriteriaBuilder().between(function,(Date) input.getArguments().get(0), (Date) input.getArguments().get(1));
        });
    }
    
   The way above expects just one argument.

**Comment by perplexhub** [comment]
Please refer to the sample below.
https://github.com/perplexhub/rsql-jpa-specification/blob/4d7a29ad55e21d254370b37ac63123077686205f/rsql-jpa/src/test/java/io/github/perplexhub/rsql/RSQLJPASupportTest.java#L53

```java
new ComparisonOperator("=between=", true)
```

- enable multiple value
