### ISSUE TITLE
Add support for ManyToMany and ManyToOne in joinHints

### ISSUE THREAD

**Issue by basven** [perplexhub/rsql-jpa-specification#52]
Current code only looks at the joinHints parameter if the join type is 1-1 or 1-many and falls back to the default inner join for other types.  I would like to have support added for the n-m and many-1 relations as well since those can be optional sometimes.

**Comment by basven** [comment]
Did you have time to take a look at the request ?

**Comment by perplexhub** [comment]
can you try 5.0.18-SNAPSHOT ?

**Comment by basven** [comment]
That snapshot is working fine for me for my test case. Thanks!

**Comment by perplexhub** [comment]
added to 5.0.18
