### ISSUE TITLE
Spring Boot starters should reuse ConversionService

### ISSUE THREAD

**Issue by manosbatsis** [perplexhub/rsql-jpa-specification#59]
Instead of "manually" trying to convert from `String` to a target type, the library should reuse converters and application settings via an `@Autowired` `ConversionService`

**Comment by perplexhub** [comment]
Which part do you mean?

**Comment by manosbatsis** [comment]
Seems to me that, with the Spring Boot starter, `RSQLVisitorBase` does not use a `ConversionService`  from the Spring context and thus does not utilize build-in or custom converters available.

**Comment by perplexhub** [comment]
As [Object to Object conversion was removed](https://github.com/perplexhub/rsql-jpa-specification/blob/5f59180ddddb8ce4f789a5619f50e14d4f31037a/rsql-common/src/main/java/io/github/perplexhub/rsql/RSQLCommonSupport.java#L48) from conversionService, I think we better not to remove it from the Spring one.

Custom converters can be add via RSQLJPASupport.addConverter().

See example [here](https://github.com/perplexhub/rsql-jpa-specification/blob/5f59180ddddb8ce4f789a5619f50e14d4f31037a/rsql-jpa/src/test/java/io/github/perplexhub/rsql/RSQLJPASupportTest.java#L609)
