### ISSUE TITLE
Duplicate from table alias when querying different attributes within OneToMany relationship

### ISSUE THREAD

**Issue by gcruz6224** [perplexhub/rsql-jpa-specification#6]
Hi,
I have this scenario: User has many roles.
RSQL: 
name=='g*^';roles.status=='Enabled';roles.type=='Create' 
When JPA creates the query it duplicates the ROLE table in FROM clause, which creates an additional unnecessary join and causes data duplication.

I am using spring-data and eclipse-link, I found that hibernate avoids duplication but I have to keep using eclipse-link.

Thanks,

**Comment by gcruz6224** [comment]
I created this PR https://github.com/perplexhub/rsql-jpa-specification/pull/7 to fix it, but it only works for JPAPredicate please give me some feedback since not sure if I consider all possible scenarios.

**Comment by perplexhub** [comment]
Implemented in 4.0.5
