### ISSUE TITLE
How to filter a long field with like or *?

### ISSUE THREAD

**Issue by e-rmartins** [perplexhub/rsql-jpa-specification#60]
Is there any way to filter a long field with like or *?

filter = "company.code==*12345*";

or 

filter = "company.code=like=12345";

**Comment by perplexhub** [comment]
Use virtual generated column to cast company code as char, then you can use like filter on the new column.

**Comment by emeGuan** [comment]
It is possible to provide an example. I don't know how to create a "virtual generated column"
Thank you
