### ISSUE TITLE
Should RSQLCommonSupport.addPropertyWhitelist be static?

### ISSUE THREAD

**Issue by luisalves00** [perplexhub/rsql-jpa-specification#64]
When we do:

```java
RSQLCommonSupport.addPropertyWhitelist(UserEntity.class,
                List.of("username", "firstName", "lastName", "email", "active"));
```

This is applied global, correct?

How can I have 2 queries to the same user entity, for to different roles: USER and ADMIN where admin can have more complex RSQL, i.e. with more properties on UserEntity whitelisted?

Shouldn't this be possible to manage per query?

**Comment by perplexhub** [comment]
https://thorben-janssen.com/hibernate-tips-map-multiple-entities-same-table/
Does above solution work for your case?

**Comment by luisalves00** [comment]
Never used this solution as I do this with mapstruct (disadvantage is that you fetch more data than needed from DB) . I guess it can be used as a complex workaround for the problem.

I think it would be cool if you could pass during the toSpecification...something like:

```java
toSpecification(final String rsqlQuery, Map<Class<?>, List<String>> whitelist, ....)
```

this way we can have it per query instead of global, which gives more control.

**Comment by perplexhub** [comment]
I've added propertyWhitelist and propertyBlacklist. Please see below links for details.

https://github.com/perplexhub/rsql-jpa-specification/blob/5f59180ddddb8ce4f789a5619f50e14d4f31037a/rsql-jpa/src/test/java/io/github/perplexhub/rsql/RSQLJPASupportTest.java#L745

https://github.com/perplexhub/rsql-jpa-specification/blob/5f59180ddddb8ce4f789a5619f50e14d4f31037a/rsql-jpa/src/test/java/io/github/perplexhub/rsql/RSQLJPASupportTest.java#L766

**Comment by perplexhub** [comment]
You can test this feature with version 5.0.20-SNAPSHOT.

**Comment by luisalves00** [comment]
Damn you are fast. Was not expecting this already. Going to try to test it right away...for what I see I'm just missing a convenience method to pass only the RSQL query string the the whitelist. Even if a wrapper object is required is better than having to add many null parameters.

**Comment by luisalves00** [comment]
@perplexhub Do you plan to release it soon?

**Comment by perplexhub** [comment]
Hi @luisalves00 , I've added ```public static <T> Specification<T> toSpecification(final QuerySupport querySupport)```, is it what you expected?

**Comment by luisalves00** [comment]
@perplexhub didn't try it out, but looks good as you have the builder pattern. That way I just build a QuerySupport with the configuration I need.

I guess I can do something like this:
```java
  userRepository.findAll(
      toSpecification(
	    QuerySupport.builder()
		   .withRsqlQuery(rsqlQuery).withPropertyWhitelist(queryWhitelist).build());
```

For me you can release it.

**Comment by perplexhub** [comment]
5.0.20
