### ISSUE TITLE
Exception hierarchy?

### ISSUE THREAD

**Issue by nstdio** [perplexhub/rsql-jpa-specification#65]
Hey @perplexhub, thanks for such a great library!

I've came across a usability problem that others might also have. Let's say we are creating specification from such query that have whitelisted, blacklisted or not found fields. There is no good way to distinguish the thrown exception because it's `IllegalArgumentException` in all three cases. I'm proposing to introduce the modest exception types to distinguish (and perhaps provide usefull information inside the thown exception) problems.

If you interested in this I could open a PR with required changes.

**Comment by perplexhub** [comment]
Hi @nstdio , please feel free to make the change, thanks for your input.
