### ISSUE TITLE
When the filter contains the rsql keyword, an exception will be reported

### ISSUE THREAD

**Issue by roiwang** [perplexhub/rsql-jpa-specification#94]
cz.jirutka.rsql.parser.RSQLParserException: cz.jirutka.rsql.parser.ParseException: Encountered " <UNRESERVED_STR> "na\u6076\u610f\u6587\u4ef6 "" at line 1, column 1541.
Was expecting one of:
    <AND> ...
    <OR> ...
    ")" ...

**Comment by perplexhub** [comment]
What's your rsql query? Did you try adding single or double quotes around the string?
